project_id = "muncie-maids"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.create-booking]
verify_jwt = false

[functions.get-booking]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-booking]
verify_jwt = false

[functions.request-photo-upload]
verify_jwt = false
